<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class NewsSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'judul_berita' => 'Peluncuran Produk Baru',
                'isi_berita' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae sem fermentum orci placerat tempus ut et arcu. Maecenas tristique ipsum sit amet orci finibus consequat. Praesent consequat diam vitae tortor vulputate, ac hendrerit odio tristique. Fusce aliquam maximus turpis, sed rutrum enim cursus quis. Curabitur faucibus mattis nisi, nec tristique nisi ultricies eget. Aenean sit amet semper quam, quis convallis neque. Vivamus congue urna quis tempus laoreet. Aliquam erat volutpat. Vestibulum convallis interdum consectetur. Proin sagittis lectus ut vulputate auctor. Aliquam tempor leo sed nisl lobortis luctus. Curabitur ac augue dui. Praesent sed diam eu felis tempor semper. Fusce nisi felis, hendrerit sed pulvinar a, pulvinar nec eros. Nulla ultrices lectus at velit auctor tincidunt. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tincidunt vehicula libero, id laoreet elit ullamcorper id. Cras nec turpis ornare, molestie mauris ornare, tempor augue. Fusce quis libero ut dui fermentum viverra ut ut magna. Integer luctus posuere metus, sed rhoncus ex. Vestibulum in enim accumsan, semper orci eu, euismod sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan, lacus ut dictum pretium, tortor libero feugiat nibh, sed convallis tortor magna vel neque. Ut tempor ultricies lorem, vitae molestie nulla fermentum suscipit. Aliquam vitae est convallis, faucibus elit a, imperdiet magna. Donec eu est dapibus, consequat est eu, luctus mauris. Nunc non facilisis libero. Quisque a accumsan mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean felis erat, volutpat quis sapien quis, euismod porttitor dolor. Pellentesque et sollicitudin augue. Vestibulum justo magna, lacinia et malesuada et, pellentesque quis leo. Praesent iaculis dignissim metus vitae posuere. Phasellus nunc augue, condimentum eget libero ut, elementum porttitor libero. Morbi rhoncus rhoncus est sed viverra. Fusce placerat dui dui, ac efficitur diam viverra in. Morbi fermentum pharetra metus, quis viverra nisi. Curabitur purus arcu, tristique et laoreet vitae, placerat et felis. Nullam accumsan tincidunt fermentum. Nam molestie aliquet est sed tristique. Vestibulum vulputate lacus non sem sollicitudin, in aliquet elit malesuada. Integer sed libero et justo lobortis ultricies vitae in arcu. Fusce sit amet justo aliquet, elementum sapien ac, aliquam augue. Etiam tristique turpis orci, vel gravida ipsum convallis vel. Aliquam et ex quis mauris scelerisque imperdiet vitae vitae neque. Proin at dictum lorem, eget euismod quam. Aenean ante ligula, vulputate a libero sed, pellentesque semper metus. Sed felis diam, finibus at nunc at, dictum eleifend nunc. Cras in nunc mi. Sed nec sodales lectus. In hac habitasse platea dictumst.',
                'gambar_berita' => 'berita-satu.jpg',
                'created_at' => '2024-06-30 08:00:00',
                'updated_at' => '2024-06-30 08:00:00',
                // 'status' => 'published',
                // 'kategori' => 'Teknologi',
            ],
            [
                'judul_berita' => 'Hasil Pemilu 2024',
                'isi_berita' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae sem fermentum orci placerat tempus ut et arcu. Maecenas tristique ipsum sit amet orci finibus consequat. Praesent consequat diam vitae tortor vulputate, ac hendrerit odio tristique. Fusce aliquam maximus turpis, sed rutrum enim cursus quis. Curabitur faucibus mattis nisi, nec tristique nisi ultricies eget. Aenean sit amet semper quam, quis convallis neque. Vivamus congue urna quis tempus laoreet. Aliquam erat volutpat. Vestibulum convallis interdum consectetur. Proin sagittis lectus ut vulputate auctor. Aliquam tempor leo sed nisl lobortis luctus. Curabitur ac augue dui. Praesent sed diam eu felis tempor semper. Fusce nisi felis, hendrerit sed pulvinar a, pulvinar nec eros. Nulla ultrices lectus at velit auctor tincidunt. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tincidunt vehicula libero, id laoreet elit ullamcorper id. Cras nec turpis ornare, molestie mauris ornare, tempor augue. Fusce quis libero ut dui fermentum viverra ut ut magna. Integer luctus posuere metus, sed rhoncus ex. Vestibulum in enim accumsan, semper orci eu, euismod sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan, lacus ut dictum pretium, tortor libero feugiat nibh, sed convallis tortor magna vel neque. Ut tempor ultricies lorem, vitae molestie nulla fermentum suscipit. Aliquam vitae est convallis, faucibus elit a, imperdiet magna. Donec eu est dapibus, consequat est eu, luctus mauris. Nunc non facilisis libero. Quisque a accumsan mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean felis erat, volutpat quis sapien quis, euismod porttitor dolor. Pellentesque et sollicitudin augue. Vestibulum justo magna, lacinia et malesuada et, pellentesque quis leo. Praesent iaculis dignissim metus vitae posuere. Phasellus nunc augue, condimentum eget libero ut, elementum porttitor libero. Morbi rhoncus rhoncus est sed viverra. Fusce placerat dui dui, ac efficitur diam viverra in. Morbi fermentum pharetra metus, quis viverra nisi. Curabitur purus arcu, tristique et laoreet vitae, placerat et felis. Nullam accumsan tincidunt fermentum. Nam molestie aliquet est sed tristique. Vestibulum vulputate lacus non sem sollicitudin, in aliquet elit malesuada. Integer sed libero et justo lobortis ultricies vitae in arcu. Fusce sit amet justo aliquet, elementum sapien ac, aliquam augue. Etiam tristique turpis orci, vel gravida ipsum convallis vel. Aliquam et ex quis mauris scelerisque imperdiet vitae vitae neque. Proin at dictum lorem, eget euismod quam. Aenean ante ligula, vulputate a libero sed, pellentesque semper metus. Sed felis diam, finibus at nunc at, dictum eleifend nunc. Cras in nunc mi. Sed nec sodales lectus. In hac habitasse platea dictumst.',
                'gambar_berita' => 'berita-dua.jpg',
                'created_at' => '2024-06-29 15:30:00',
                'updated_at' => '2024-06-29 15:30:00',
                //'status' => 'published',
                //'kategori' => 'Politik',
            ],
            [
                'judul_berita' => 'Tips Menjaga Kesehatan di Musim Pandemi',
                'isi_berita' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae sem fermentum orci placerat tempus ut et arcu. Maecenas tristique ipsum sit amet orci finibus consequat. Praesent consequat diam vitae tortor vulputate, ac hendrerit odio tristique. Fusce aliquam maximus turpis, sed rutrum enim cursus quis. Curabitur faucibus mattis nisi, nec tristique nisi ultricies eget. Aenean sit amet semper quam, quis convallis neque. Vivamus congue urna quis tempus laoreet. Aliquam erat volutpat. Vestibulum convallis interdum consectetur. Proin sagittis lectus ut vulputate auctor. Aliquam tempor leo sed nisl lobortis luctus. Curabitur ac augue dui. Praesent sed diam eu felis tempor semper. Fusce nisi felis, hendrerit sed pulvinar a, pulvinar nec eros. Nulla ultrices lectus at velit auctor tincidunt. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam tincidunt vehicula libero, id laoreet elit ullamcorper id. Cras nec turpis ornare, molestie mauris ornare, tempor augue. Fusce quis libero ut dui fermentum viverra ut ut magna. Integer luctus posuere metus, sed rhoncus ex. Vestibulum in enim accumsan, semper orci eu, euismod sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan, lacus ut dictum pretium, tortor libero feugiat nibh, sed convallis tortor magna vel neque. Ut tempor ultricies lorem, vitae molestie nulla fermentum suscipit. Aliquam vitae est convallis, faucibus elit a, imperdiet magna. Donec eu est dapibus, consequat est eu, luctus mauris. Nunc non facilisis libero. Quisque a accumsan mauris. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean felis erat, volutpat quis sapien quis, euismod porttitor dolor. Pellentesque et sollicitudin augue. Vestibulum justo magna, lacinia et malesuada et, pellentesque quis leo. Praesent iaculis dignissim metus vitae posuere. Phasellus nunc augue, condimentum eget libero ut, elementum porttitor libero. Morbi rhoncus rhoncus est sed viverra. Fusce placerat dui dui, ac efficitur diam viverra in. Morbi fermentum pharetra metus, quis viverra nisi. Curabitur purus arcu, tristique et laoreet vitae, placerat et felis. Nullam accumsan tincidunt fermentum. Nam molestie aliquet est sed tristique. Vestibulum vulputate lacus non sem sollicitudin, in aliquet elit malesuada. Integer sed libero et justo lobortis ultricies vitae in arcu. Fusce sit amet justo aliquet, elementum sapien ac, aliquam augue. Etiam tristique turpis orci, vel gravida ipsum convallis vel. Aliquam et ex quis mauris scelerisque imperdiet vitae vitae neque. Proin at dictum lorem, eget euismod quam. Aenean ante ligula, vulputate a libero sed, pellentesque semper metus. Sed felis diam, finibus at nunc at, dictum eleifend nunc. Cras in nunc mi. Sed nec sodales lectus. In hac habitasse platea dictumst.',
                'gambar_berita' => 'berita-tiga.jpg',
                'created_at' => '2024-06-28 10:45:00',
                'updated_at' => '2024-06-28 10:45:00',
                //'status' => 'draft',
                //'kategori' => 'Kesehatan',
            ],
        ];

        foreach ($data as $berita) {
            // insert semua data ke tabel
            $this->db->table('news')->insert($berita);
        }
    }
}
